server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

---

spring:
  profiles:
    active: prod


---

spring:
  profiles:
    active: local


---

spring:
  profiles:
    include:
      - oauth
      - endpoint