-- FOOD RECOMMENDATION 1:N 관계로 변경 --

ALTER TABLE RECOMMENDATION CHANGE COLUMN NAME FOOD_ID BIGINT NOT NULL;

ALTER TABLE RECOMMENDATION
    ADD CONSTRAINT FK_RECOMMENDATION_FOOD_ID_FOOD_ID FOREIGN KEY (FOOD_ID)
        REFERENCES FOOD (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
