-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- CATEGORY Table Create SQL
CREATE TABLE IF NOT EXISTS CATEGORY
(
    `ID`           BIGINT          NOT NULL    AUTO_INCREMENT,
    `NAME`         VARCHAR(255)    NOT NULL,
    `CREATED_AT`   DATETIME        NOT NULL,
    `MODIFIED_AT`  DATETIME        NULL,
    CONSTRAINT PK_CATEGORY PRIMARY KEY (ID)
);


-- FOOD Table Create SQL
CREATE TABLE IF NOT EXISTS FOOD
(
    `ID`           BIGINT          NOT NULL    AUTO_INCREMENT,
    `NAME`         VARCHAR(255)    NOT NULL,
    `IMG_URL`      BLOB            NOT NULL,
    `INTRODUCE`    VARCHAR(255)    NOT NULL,
    `CATEGORY_ID`  BIGINT          NOT NULL,
    `CREATED_AT`   DATETIME        NOT NULL,
    `MODIFIED_AT`  DATETIME        NULL,
    CONSTRAINT PK_FOOD PRIMARY KEY (ID)
);

ALTER TABLE FOOD
    ADD CONSTRAINT FK_FOOD_CATEGORY_ID_CATEGORY_ID FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORY (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;


-- RECOMMENDATION Table Create SQL
CREATE TABLE IF NOT EXISTS RECOMMENDATION
(
    `ID`           BIGINT          NOT NULL    AUTO_INCREMENT,
    `NAME`         VARCHAR(255)    NOT NULL,
    `CREATED_AT`   DATETIME        NOT NULL,
    `MODIFIED_AT`  DATETIME        NULL,
    CONSTRAINT PK_RECOMMENDATION PRIMARY KEY (ID)
);


-- USER Table Create SQL
CREATE TABLE IF NOT EXISTS USER
(
    `ID`                   BIGINT          NOT NULL    AUTO_INCREMENT,
    `NAME`                 VARCHAR(255)    NOT NULL,
    `EMAIL`                VARCHAR(255)    NULL,
    `SOCIAL_PROVIDER_KEY`  VARCHAR(255)    NOT NULL,
    `PROFILE_IMG`          VARCHAR(255)    NULL,
    `ROLE`                 VARCHAR(255)    NOT NULL,
    `SOCIAL`               VARCHAR(255)    NOT NULL,
    `CREATED_AT`           DATETIME        NOT NULL,
    `MODIFIED_AT`          DATETIME        NULL,
    CONSTRAINT PK_USER PRIMARY KEY (ID)
);


-- FOOD_INGREDIENT Table Create SQL
CREATE TABLE IF NOT EXISTS FOOD_INGREDIENT
(
    `ID`             BIGINT          NOT NULL    AUTO_INCREMENT,
    `FOOD_ID`        BIGINT          NOT NULL,
    `INGREDIENT_01`  VARCHAR(255)    NULL,
    `INGREDIENT_02`  VARCHAR(255)    NULL,
    `INGREDIENT_03`  VARCHAR(255)    NULL,
    `INGREDIENT_04`  VARCHAR(255)    NULL,
    `INGREDIENT_05`  VARCHAR(255)    NULL,
    `INGREDIENT_06`  VARCHAR(255)    NULL,
    `INGREDIENT_07`  VARCHAR(255)    NULL,
    CONSTRAINT PK_FOOD_INGREDIENT PRIMARY KEY (ID)
);


-- FOOD_RECOMMENDATION Table Create SQL
CREATE TABLE IF NOT EXISTS FOOD_RECOMMENDATION
(
    `ID`                 BIGINT      NOT NULL    AUTO_INCREMENT,
    `FOOD_ID`            BIGINT      NOT NULL,
    `RECOMMENDATION_ID`  BIGINT      NOT NULL,
    `CREATED_AT`         DATETIME    NOT NULL,
    `MODIFIED_AT`        DATETIME    NULL,
    CONSTRAINT PK_FOOD_RECOMMENDATION PRIMARY KEY (ID)
);

ALTER TABLE FOOD_RECOMMENDATION
    ADD CONSTRAINT FK_FOOD_RECOMMENDATION_FOOD_ID_FOOD_ID FOREIGN KEY (FOOD_ID)
        REFERENCES FOOD (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE FOOD_RECOMMENDATION
    ADD CONSTRAINT FK_FOOD_RECOMMENDATION_RECOMMENDATION_ID_RECOMMENDATION_ID FOREIGN KEY (RECOMMENDATION_ID)
        REFERENCES RECOMMENDATION (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;


