CREATE TABLE USER_RECOMMENDATION
(
    `ID`                 BIGINT      NOT NULL    AUTO_INCREMENT,
    `RECOMMENDATION_ID`  BIGINT      NOT NULL,
    `USER_ID`            BIGINT      NOT NULL,
    `CREATED_AT`         DATETIME    NOT NULL,
    `MODIFIED_AT`        DATETIME    NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE USER_RECOMMENDATION
    ADD CONSTRAINT FK_USER_RECOMMENDATION_USER_ID_USER_ID FOREIGN KEY (USER_ID)
        REFERENCES USER (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE USER_RECOMMENDATION
    ADD CONSTRAINT FK_USER_RECOMMENDATION_RECOMMENDATION_ID_RECOMMENDATION_ID FOREIGN KEY (RECOMMENDATION_ID)
        REFERENCES RECOMMENDATION (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
