-- MYPICK Table Create SQL
CREATE TABLE IF NOT EXISTS MYPICK
(
    `ID`           BIGINT      NOT NULL    AUTO_INCREMENT,
    `USER_ID`      BIGINT      NOT NULL,
    `FOOD_ID`      BIGINT      NOT NULL,
    `CREATED_AT`   DATETIME    NOT NULL,
    `MODIFIED_AT`  DATETIME    NULL,
    CONSTRAINT PK_MYPICK PRIMARY KEY (ID)
    );

ALTER TABLE MYPICK
    ADD CONSTRAINT FK_MYPICK_FOOD_ID_FOOD_ID FOREIGN KEY (FOOD_ID)
        REFERENCES FOOD (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MYPICK
    ADD CONSTRAINT FK_MYPICK_USER_ID_USER_ID FOREIGN KEY (USER_ID)
        REFERENCES USER (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
